### ISSUE TITLE
Shouldn't imported variables be read-only?

### ISSUE THREAD

**Issue by stefan-b314** [rollup/d3-jsnext#1]
Hi,

I really like what you are doing here and with [rollup](https://github.com/rollup/rollup)!

Currently I am working with [jspm](http://jspm.io/) and tried to use d3-jsnext – although, as I understand from your rollup README, using jspm and alike does import everything first (tree-shaking approach).

After I had configured jspm to work with d3-jsnext, I stumbled over variable read-only errors:

```
[...]/d3-jsnext@3.5.5/src/geo/path.js:35:5: d3_geo_pathAreaSum is read-only
```

After looking at [the code](https://github.com/rollup/d3-jsnext/blob/master/src/geo/path.js#L35), I think this seems to be right – as imported variables should be handled as read-only, shouldn't they?

Currently, I don't know how to solve this in d3-jsnext and/or rollup, as I am just starting digging deeper in ES6 module loading, but I wanted to inform you about this issue.

Kind regards
Stefan

**Comment by Rich-Harris** [comment]
Ah, thanks - didn't know about that one. There are a few places where modules assign to things that they don't create, which you can't do in ES6 - `d3.event` is another good example, for now I'm [cheating](https://github.com/rollup/d3-jsnext/blob/master/src/selection/selection.js#L645) by using `window.d3_event`. Something similar may be required here. 

Having said all that, have you seen the work on d3 4.0? It's now going to be composed entirely of ES6 modules, spread across several repos (and using Rollup to create UMD bundles), and as such this research project is a bit obsolete (which is brilliant - exactly the outcome it was designed to achieve!). As such I wasn't planning to do much more work on it. If you're using JSPM then for the time being you might be better off using 'proper' d3, since you don't currently get the bundling benefits anyway. Hope that's not too much of a nuisance.

Incidentally, a lot of d3 4.0 is ready to use already (unfortunately the geo module isn't one of them yet) - you can see progress [here](https://github.com/mbostock/d3/issues/2461).

**Comment by stefan-b314** [comment]
Thank you!
